---

- name: For file mode, adapt the filename
  ansible.builtin.set_fact:
    autoinstall_path: "{{ autoinstall_path | regex_replace('\\.iso', '.yml') }}"

- name: Copy customized user-data
  ansible.builtin.template:
    src: "{{ autoinstall_template }}"
    dest: "{{ autoinstall_path }}"
    mode: "0600"
  tags: molecule-idempotence-notest
