---

- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
  changed_when: false
  register: __tmpdir

- name: Set temporary filename
  ansible.builtin.set_fact:
    autoinstall_path_tmp: "{{ autoinstall_path }}.tmp"

- name: Create directory to store user-data and meta-data
  ansible.builtin.file:
    path: "{{ os_iso_tmpdir }}/autoinstall"
    state: directory
    mode: "0755"
  changed_when: false

- name: Copy customized user-data
  ansible.builtin.template:
    src: "{{ autoinstall_distro }}/user-data-{{ autoinstall_bios_mode }}.yml.j2"
    dest: "{{ os_iso_tmpdir }}/autoinstall/user-data"
    remote_src: yes
    mode: "666"
  changed_when: false

- name: Create empty meta-data file in directory
  ansible.builtin.file:
    path: "{{ os_iso_tmpdir }}/autoinstall/meta-data"
    state: touch
    mode: "666"
  changed_when: false

- name: Copy result to final location
  ansible.builtin.template:
    src: "{{ autoinstall_path_tmp }}"
    dest: "{{ autoinstall_path }}"
    remote_src: yes
    mode: "666"

- name: Delete temporay directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ __tmpdir.path }}"
    - "{{ autoinstall_path_tmp }}"
  changed_when: false
